### PR TITLE
Pull request to merge the branch

### PR DESCRIPTION
**Pull request by Dipeshtwis**
To merge Embedding_images_and_Video branch into the master branch.

### CODE REVIEW

**Comment by uryelah** [comment]
Hello **Yiğit Mersin & Twister Kumar**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all welcome to Microverse and congrats on your first project 🌟**

There are still some issues to fix before going to the next project, but you got this!💪 

---------     

## Required Changes 🏗 👷‍♀ 

- Never close a Pull Request after review, you should make the requested changes in the same branch and submit the same Pull Request link for the next review.

- [x] Re-write your Pull Request message so it follows the model below like mentioned in the last review too:
pr_message

- [x] Make sure your [HTML passes the validation without any errors or warnings.](https://validator.w3.org)

- [x] Remember to follow [commit writing best practices ](https://chris.beams.io/posts/git-commit/)from now on:
  - Write your commit messages using the imperative tense
  - Capitalize your commits

- [x] The right area of the navbar should have at least 3 images.

- [x] Style your navbar button and input better so they have the same height and proximity like the original youtube page.

- [x] The logo and left burger icon are blurry. Don't use low-resolution images for that.
You can use a service like [font awesome](fontawesome.com/) for icons and search for a Youtube logo online, search for a png image with a transparent background, and Youtube icon, or svg image.
[Read this article if you are not sure about the best images to use in each case.](https://cheesecakelabs.com/blog/jpg-png-svg-web-beginners-guide/)

- [x] The 'Share' element under the video should be a `button`, not an `a` tag.
----

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by Dipeshtwis** [comment]
We upgrade the project which includes

- icons inserted from awesome-font.
- include the share button.
- navbar button and search bar are of the same height and proximity.
- the right area of the navbar has 4 items.
- pass the Html and CSS validation with no error.

**Comment by lekegitrepo** [comment]
#### Hi @Dipeshtwis and @yigitm :1st_place_medal: 
#### Good job for implementing the required changes mentioned in the last review. This project is approved.

### Reviewed by Temitayo Adeleke.

**Review by lekegitrepo — APPROVED** [review]
#### Status: Approved.

**Pull request merged**
